---
layout: post
title: "异常体系与项目实践"
date: "2023-05-19T01:08:13.878Z"
---
异常体系与项目实践
=========

![异常体系与项目实践](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518230945058-1275751652.png) 程序中的异常可以反映系统的缺陷和待优化的点，并且是无法完全避免的，如何处理异常和降低异常出现的频率，是系统质量的基础保障；随着分布式架构的流行，各种复杂的请求链路给异常处理带来了巨大的麻烦；

> 程序式阴影：为什么不报错？

一、简介
====

在程序开发的过程中，异常处理从来都是一个复杂的维度，无论是新手还是经验老到的选手，在编码时都会面对各种异常情况；

程序中的异常可以反映系统的缺陷和待优化的点，并且是无法完全避免的，如何处理异常和降低异常出现的频率，是系统质量的基础保障；

随着分布式架构的流行，各种复杂的请求链路给异常处理带来了巨大的麻烦，需要全面的监控来定位原因，才能快速的优化和解决；

二、异常体系
======

不论是JDK基础，还是各类组件，在源码中都涉及大量的异常封装，从而精确的反映出描述信息，先来看看Java中的异常体系基础；

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221623527-1675060500.png)

**Throwable**：是所有错误「Error」和异常「Exception」的超类，

**Error**：通常是底层的不可恢复的类，此类错误一般都比较严重，JVM将终止其运行的线程；

**Exception**：程序自身可以捕获并且可以预处理的异常，例如捕获处理或者抛出；

针对「编译器」来说，异常又分为「检查」异常和「非检查」异常；

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221626473-1926610201.png)

**检查异常**：即编译时异常，在编译时期就会被编译器查验到的异常，这类异常要么捕获处理要么抛出，否则就会报编译错误；

**非检查异常**：即运行时异常，在编译时期不会被编译器查验到的异常，这类异常只有在程序运行的时候，才会有可能被抛出；

三、异常用法
======

1、使用细节
------

Java异常处理关键字，分别是：「try」可能抛异常的代码块，「catch」捕获异常、「finally」必须执行的代码块、「throw」方法内抛指定异常、「throws」方法声明抛多个异常；

    public class UseExe01 {
        public static void main(String[] args) {
            try {
                strStm ();
                ioStm();
            } catch (NullPointerException e) {
                System.out.println("空指针异常："+e.getMessage());
                e.printStackTrace();
            } catch (IOException e) {
                System.out.println("IO流异常："+e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                System.out.println("异常："+e.getMessage());
                e.printStackTrace();
            } finally {
                System.out.println("execute...finally");
            }
        }
        public static void ioStm () throws FileNotFoundException {
            new FileInputStream(new File("file_path"));
        }
        public static String strStm () throws NullPointerException {
            Object object = new Object() ;
            return object.getClass().getName() ;
        }
    }
    

**案例分析**

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221630648-710369310.png)

**细节分析**

*   如果「try」代码块中没有抛出异常，执行完会跳到「finally」代码块；
*   如果「try」代码块中抛出异常，则执行「catch」代码块，无论是否捕获异常，最终都要执行「finally」代码块；
*   可以存在多个「catch」代码块，但是最多只匹配一个异常；
*   捕获异常与抛出异常的类型可以匹配，或者捕获异常的类型是抛出异常的父类；
*   在异常捕获时，同一个继承体系内，先捕获子类异常，再捕获父类异常；

2、返回值问题
-------

在异常处理逻辑中，有一个非常经典的问题，就是「return」返回值，如果在「try.catch.finally」代码块中都存在「return」关键字，则要分情况讨论；

### 2.1 值类型

    public class UseExe02 {
        // 返回【2】
        public static int getInt1 () {
            try {
                int i = 1 / 0;
            } catch (ArithmeticException e){
                e.printStackTrace();
                return 1;
            } finally {
                System.out.println("execute...finally");
                return 2;
            }
        }
        // 返回【1】
        public static int getInt2 () {
            int a = 1;
            try{
                int i = 1/0;
                return a;
            }catch (ArithmeticException e){
                e.printStackTrace();
                return a;
            }finally {
                ++a;
                System.out.println("execute...finally");
            }
        }
        // 返回【3】
        public static int getInt3 () {
            int a = 1;
            try{
                int i = 1/0;
                a++;
                return a ;
            }catch (ArithmeticException e){
                a++;
                e.printStackTrace();
            }finally {
                a++;
                System.out.println("execute...finally");
            }
            return a ;
        }
    }
    

**逻辑分析**

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221638182-846576750.png)

### 2.2 引用类型

    public class UseExe03 {
        // 返回【张三】
        public static String getStr1 () {
            String var ;
            try {
                var = new String("张三");
                return var ;
            } catch (ArithmeticException e){
                e.printStackTrace();
            } finally {
                var = new String("李四");
                System.out.println("execute...finally："+var);
            }
            return var ;
        }
        // 返回【李四】
        public static String getStr2 () {
            String var ;
            try{
                int i = 1/0;
                var = new String("张三");
                return var;
            }catch (ArithmeticException e){
                e.printStackTrace();
                var = new String("李四");
                return var;
            }finally {
                var = new String("王五");
                System.out.println("execute...finally："+var);
            }
        }
        // 返回【王五】
        public static String getStr3 () {
            String var ;
            try{
                int i = 1/0;
                var = new String("张三");
                return var ;
            }catch (ArithmeticException e){
                var = new String("李四");
                e.printStackTrace();
            }finally {
                var = new String("王五");
                System.out.println("execute...finally："+var);
            }
            return var ;
        }
    }
    

**逻辑分析**

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221641118-470788354.png)

### 2.3 结论说明

*   如果只有「try」代码块中有「return」关键字，逻辑执行正常则得到「try」处的返回值；
*   如果只有「try.catch」代码块中有「return」关键字，「try」代码块异常，「catch」代码块执行正常，则得到「catch」处的返回值；
*   如果「finally」代码块中有「return」关键字，当该代码块执行正常时会得到此处的返回值；

值得说明的一点是，从异常的设计原理来来说，并不推荐在「finally」代码块中使用「return」关键字，可能会导致程序提前结束，这也是常见的开发规范；

四、项目实践
======

1、异常定义
------

对于复杂的分布式工程来说，系统发生问题时，十分依赖异常信息的捕获，从而快速定位原因和解决；

项目在处理异常时，需要考虑两个核心维度：「1」捕获和解决异常信息，「2」传递异常信息到应用端，从而引导用户的动作；

在系统中，通常依赖很多自定义的异常，比如常见：系统异常，业务异常，第三方异常；基本都是「运行时」异常；

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221644106-463254864.png)

**系统异常**：比如超时请求或者服务级别异常，导致流程无法执行，需要研发人员介入处理；

**业务异常**：基于响应的提示信息，用户可以自行解决的问题，比如常见的参数校验，授权问题等；

**第三方异常**：可以是内部不同系统的交互，也可以是第三方的交互，可能会涉及到各种响应状态，通过内部的封装进行统一管理，并且要保留第三方的响应；

2、异常封装
------

基于运行时异常「RuntimeException」类，分别定义「系统」、「业务」、「第三方」三类异常；

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221646872-1217271302.png)

自定义异常基础类，**注意此处省略很多构造方法，作为「RuntimeException」的子类，具体参考其源码的构造方法即可；**

    public class BaseExe extends RuntimeException {
        private String code ;
        public BaseExe (String code,String msg) {
            super(msg);
            this.code = code ;
        }
        public BaseExe(String message, Throwable cause) {
            super(message, cause);
        }
        // 省略其他构造方法
    }
    

系统异常类，并提供常用的系统异常信息枚举类；

    public enum SysExeCode {
        SYSTEM_EXE("S00000", "系统异常");
    }
    public class SysException extends BaseExe {
        public SysException(String code, String msg) {
            super(code, msg);
        }
        public SysException(SysExeCode sysExeCode) {
            super(sysExeCode.getCode(), sysExeCode.getMsg());
        }
    }
    

业务异常类，并提供常用的业务异常信息枚举类；

    public enum BizExeCode {
        BIZ_EXE("B00000", "业务异常");
    }
    public class BizException extends BaseExe {
        public BizException(String code, String msg) {
            super(code, msg);
        }
        public BizException(BizExeCode bizExeCode) {
            super(bizExeCode.getCode(), bizExeCode.getMsg());
        }
    }
    

第三方异常类，并提供常用的第三方异常信息枚举类；

    public enum ThirdExeCode {
        THIRD_EXE("T00000", "第三方异常");
    }
    public class ThirdException extends BaseExe {
        // 第三方交互异常响应信息
        private String thirdCode ;
        private String thirdMsg ;
        public ThirdException(String code, String msg) {
            super(code, msg);
        }
        public ThirdException(String code, String msg,String thirdCode,String thirdMsg) {
            super(code, msg);
            this.thirdCode = thirdCode ;
            this.thirdMsg = thirdMsg ;
        }
        public ThirdException(ThirdExeCode thirdExeCode,String thirdCode,String thirdMsg) {
            super(thirdExeCode.getCode(), thirdExeCode.getMsg());
            this.thirdCode = thirdCode ;
            this.thirdMsg = thirdMsg ;
        }
    }
    

从开发规范来说，不允许在代码中随意添加异常描述信息，必须都维护在相应的枚举类中，不同的异常类型，要在合适的场景下抛出，尽量由最上层统一捕获并处理，再转换为统一的响应结果；

3、异常处理
------

### 3.1 响应方式

在微服务项目中，通常采用`RestControllerAdvice`和`ExceptionHandler`注解，实现全局异常的捕获和处理；

    @RestControllerAdvice
    public class ExeHandler {
        /**
         * 默认异常
         */
        @ExceptionHandler(value = Exception.class)
        public void defaultException(Exception e) {
            // 统一返回
        }
        /**
         * 系统异常
         */
        @ExceptionHandler(value = SysException.class)
        public void sysException(SysException e) {
            // 统一返回
        }
        /**
         * 业务异常
         */
        @ExceptionHandler(value = BizException.class)
        public void bizException(BizException e) {
            // 统一返回
        }
        /**
         * 第三方异常
         */
        @ExceptionHandler(value = ThirdException.class)
        public void thirdException(ThirdException e) {
            // 统一返回
        }
    }
    

### 3.2 记录方式

通常在一些核心的业务流程中，会通过注解的方式记录日志，于研发而言，最关心的还是异常日志，以此为逻辑优化的关键依据；

比较常用的技术手段是自定义注解+切面编程来实现，细节参考开源仓库中《集成日志，复杂业务下的自定义实现》篇幅内容；

    @Component
    @Aspect
    public class LogAop {
        /**
         * 日志切入点
         */
        @Pointcut("@annotation(com.defined.log.annotation.DefinedLog)")
        public void logPointCut() {
        }
        /**
         * 环绕切入
         */
        @Around("logPointCut()")
        public Object around (ProceedingJoinPoint proceedingJoinPoint) {
            try{
                // 执行方法
                result = proceedingJoinPoint.proceed();
            } catch (SysException e){
                // 系统异常
            } catch (BizException e){
                // 业务异常
            } catch (ThirdException e){
                // 第三方异常
            } catch (Exception e){
                // 默认异常
            } finally {
                // 信息处理
            }
            return result ;
        }
    }
    

4、异常通知
------

抛开业务异常不说，对于「系统」和「第三方」异常，通常都会第一时间触达到研发，从而快速定位原因和处理；

一般会根据异常的级别，将进行不同维度的消息触达，比如某微，某钉，邮件，短信等；

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221649581-1506470426.png)

从技术的实现上来看，常规也是采用切面编程的方式，细节参考开源仓库中《基于AOP切面，实现系统告警功能》篇幅内容；关于消息中心的搭建设计，同样可以参考开源仓库中《聊聊消息中心的设计与实现逻辑》篇幅内容；

5、系统故障
------

从系统架构的层面来分析，大部分组件都提供了必要的监控能力，而这种监控手段的核心价值在于快速发现故障，并且提供一定的分析能力；

比如分布式系统中，复杂的请求的链路，对于故障的定位和排查难度都是极大的，需要将各种组件的监控信息进行统筹分析；

**系统层面监控**

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221652283-1969793976.png)

**请求链路分析**

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221655570-575602753.png)

**日志记录能力**

![](https://img2023.cnblogs.com/blog/1691717/202305/1691717-20230518221658446-1550796199.png)

可以从关键的日志记录作为问题切入点，再基于系统层面的监控能力缩小问题范围，分析请求链路的异常原因，最后通过完整的日志分析细节，从而提升问题解决的效率；

关于这些技术的应用，在开源仓库中都有详细案例，此处不再赘述；

五、参考源码
======

    编程文档：
    https://gitee.com/cicadasmile/butte-java-note
    
    应用仓库：
    https://gitee.com/cicadasmile/butte-flyer-parent
    

**Gitee主页：** [https://gitee.com/cicadasmile/butte-java-note](https://gitee.com/cicadasmile/butte-java-note)